import { methodsReport } from './reports.mjs';
import { site, research, notes, caseStudy, articleBodies, phronemeProject } from './content.mjs';

const esc = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[c]));
const arrow = '<span aria-hidden="true">↗</span>';
const link = (url, label, classes = '') => `<a class="${classes}" href="${esc(url)}">${label} ${arrow}</a>`;

function header() {
  return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="shell header-inner"><a class="wordmark" href="/" aria-label="Owen Crabbe home"><span class="brand-mark" aria-hidden="true"></span>owen crabbe<span class="wordmark-period">.</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="site-nav">Menu <span aria-hidden="true">+</span></button><nav id="site-nav" aria-label="Main navigation"><a href="/#work">Work</a><a href="/#writing">Publications</a><a href="/research/">Research</a><a href="/#about">About</a></nav>${link(`mailto:${site.email}`, 'Get in touch', 'header-contact')}</div></header>`;
}

function footer() {
  return `<footer class="site-footer"><div class="shell footer-inner"><p>© 2026 Owen Crabbe</p><p>Applied AI. Open questions. Inspectable work.</p><div>${link(site.github, 'GitHub')}${link(`mailto:${site.email}`, 'Email')}</div></div></footer>`;
}

function page(path, title, description, body, cls = '') {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} — Owen Crabbe</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#f8f7f3"><link rel="canonical" href="${site.origin}${path}"><meta property="og:title" content="${esc(title)} — Owen Crabbe"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="${(path.includes('/writing/') || path.includes('/publications/')) ? 'article' : 'website'}"><meta property="og:url" content="${site.origin}${path}"><meta property="og:site_name" content="Owen Crabbe"><meta name="twitter:card" content="summary"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/styles.css"><script src="/assets/main.js" defer></script></head><body class="${cls}">${header()}<main id="main" tabindex="-1">${body}</main>${footer()}</body></html>`;
}

function sectionHeading(number, eyebrow, title, extra = '') {
  return `<div class="section-heading"><div><p class="eyebrow"><span class="section-number">${number}</span>${eyebrow}</p><h2>${title}</h2></div>${extra}</div>`;
}

function projectVisual() {
  return `<div class="project-visual" role="img" aria-label="Conceptual system sketch: evidence sources connect to analysis and an investigation brief."><div class="visual-label"><span class="status-dot" aria-hidden="true"></span> System sketch</div><svg class="map-grid" viewBox="0 0 600 460" aria-hidden="true"><defs><pattern id="grid" width="42" height="42" patternUnits="userSpaceOnUse"><path d="M 42 0 L 0 0 0 42" fill="none" stroke="currentColor" stroke-width="1"/></pattern></defs><rect width="600" height="460" fill="url(#grid)"/><path d="M-20 310L138 192L236 256L390 100L620 216M-10 40L180 166L280 136L446 298L600 274M66 500L210 320L156 244L286 -25" fill="none" stroke="currentColor" stroke-width="2"/><path d="M242 222L318 176L384 216L338 284L266 272Z" fill="currentColor" opacity=".18"/><path d="M242 222L318 176L384 216L338 284L266 272Z" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="315" cy="230" r="7" fill="#e0ffb7"/><circle cx="315" cy="230" r="18" fill="none" stroke="#e0ffb7" stroke-width="1"/></svg><div class="map-note map-note-one"><span>01 / Source evidence</span><strong>Traceable inputs</strong><div class="tiny-line"></div><div class="tiny-line short"></div></div><div class="map-note map-note-two"><span>02 / Analysis</span><strong>Explicit assumptions</strong><div class="evidence-tags"><i>Sources</i><i>Scenarios</i></div></div><div class="map-note map-note-three"><span>03 / Investigation brief</span><strong>Questions to verify <b aria-hidden="true">↗</b></strong><div class="tiny-line"></div><div class="tiny-line short"></div></div><span class="visual-coordinate">Sources → reasoning → review</span></div>`;
}

function workIndex() {
  return `<aside class="work-index" aria-labelledby="record-heading"><div class="record-heading"><p class="eyebrow">A public record of the work</p><span aria-hidden="true">↗</span></div><h2 id="record-heading">Built. Written.<br> Open to inspection.</h2><a class="record-row" href="#work"><span class="record-number">01</span><span><strong>Projects</strong><small>Cividian Site Diligence & Phroneme</small></span><span aria-hidden="true">↓</span></a><a class="record-row" href="#writing"><span class="record-number">02</span><span><strong>Technical writing</strong><small>Two self-published engineering notes</small></span><span aria-hidden="true">↓</span></a><a class="record-row" href="/research/"><span class="record-number">03</span><span><strong>Research in progress</strong><small>Three proposed studies · no results yet</small></span><span aria-hidden="true">↗</span></a><p class="record-note">Follow the artifact, then the claim.</p></aside>`;
}

function home() {
  const noteCards = notes.map(note => `<article class="note-card"><p class="eyebrow">Self-published engineering note<span class="note-number">${note.number}</span></p><h3><a href="/writing/${note.slug}/">${note.title}</a></h3><p>${note.description}</p><div class="note-bottom"><span>${note.reading} · September 2026</span>${link(`/writing/${note.slug}/`, '<span class="sr-only">Read '+note.title+'</span>', 'round-arrow')}</div></article>`).join('');
  const researchRows = research.map(item => `<li><span class="research-number">${item.number}</span><div><h3>${item.title}</h3><p>${item.description}</p></div><span class="research-state">Proposed</span></li>`).join('');
  return page('/', 'Applied AI / research engineering', 'Owen Crabbe’s public record of applied AI projects, source-linked case studies, self-published technical writing, and proposed research.', `
  <section class="hero shell"><div class="hero-copy"><p class="eyebrow"><span class="blue-rule" aria-hidden="true"></span>Owen Crabbe / Applied AI & research engineering</p><h1>Applied AI.<br> Real-world<br> <em>questions.</em></h1><p class="hero-description">I build tools for real estate research, evidence review, and planning. This is a record of the systems I’m building, what their source code shows, and the questions still worth testing.</p><div class="hero-actions"><a class="button button-primary" href="#work">See the projects <span aria-hidden="true">↓</span></a><a class="text-link" href="#writing">Explore the writing ${arrow}</a></div><p class="hero-disciplines">Projects <span aria-hidden="true">/</span> Technical writing <span aria-hidden="true">/</span> Research in progress</p></div>${workIndex()}</section>
  <div class="shell"><div class="hero-bottom"><span>Working artifacts. Visible assumptions.</span><span>A portfolio with a source trail.</span><span class="scroll-hint" aria-hidden="true">↓</span></div></div>
  <section class="work-section shell" id="work">${sectionHeading('01', 'Selected projects', 'From question to working system.', '<p class="section-aside">Explore the implementation,<br> the decisions, and the limits.</p>')}
  <article class="featured-project"><div class="project-copy"><p class="eyebrow"><span class="project-kicker">Real estate research</span><span>Public implementation</span></p><h3><a href="/work/cividian/">Cividian<br> Site Diligence<span aria-hidden="true">↗</span></a></h3><p>Turn a site question into an investigation brief. Connect parcel identity, source evidence, financial scenarios, and bounded AI reasoning while keeping assumptions visible.</p><div class="project-tags"><span>Evidence retrieval</span><span>Scenario analysis</span><span>Citation checks</span></div><p class="project-evidence"><strong>Evidence:</strong> public source and scripted evaluation cases. Live factual accuracy has not been established by those cases.</p><div class="project-links">${link('/work/cividian/', 'Read the case study', 'project-main-link')}${link(site.repo, 'Inspect the source')}${link(site.demo, 'Explore the demo')}</div></div>${projectVisual()}</article>
  <article class="phroneme-project"><div class="phroneme-mark" aria-hidden="true"><span>Plan</span><span>Act</span><span>Reflect</span><span class="phroneme-loop">↻</span></div><div class="phroneme-copy"><p class="eyebrow">Planning & reflection / Working product</p><h3><a href="/work/mindforge/">Phroneme</a></h3><p>A browser-local activity journal and an open-source evidence toolkit. Plan a week, record what happened, and keep the source relationships and uncertainty in view.</p><p class="project-evidence"><strong>Evidence:</strong> public journal and validator code, plus 54 software tests at the linked revision. Reasoning and health outcomes remain unevaluated.</p><div class="project-links">${link('/work/mindforge/', 'Read the case study', 'project-main-link')}${link(site.fitnessLab, 'Try Fitness Lab')}${link(site.mindforge, 'Inspect the toolkit')}</div></div></article>
  <div class="project-standard"><span class="eyebrow">How to read the work</span><p>Case studies connect implementation to evidence. A software test, a model evaluation, and a real-world outcome answer different questions.</p>${link('/writing/verification-boundaries/', 'Read about verification boundaries', 'text-link')}</div></section>
  <section class="writing-section shell" id="writing">${sectionHeading('02', 'Publications & technical writing', 'Notes from the build.', '<p class="section-aside">Self-published analysis.<br> September 2026.</p>')}<p class="publication-context">These engineering notes explain the work and its limits. They are self-published technical writing, not peer-reviewed papers.</p><article class="report-card"><p class="eyebrow">Technical report · ${esc(methodsReport.status)} · ${esc(methodsReport.peerReview)}</p><h3><a href="/publications/${methodsReport.slug}/">${esc(methodsReport.title)}</a></h3><p>${esc(methodsReport.description)}</p><p>Published ${esc(methodsReport.date)}. No live benchmark outcomes are reported.</p>${link('/publications/'+methodsReport.slug+'/', 'Read the technical report', 'text-link')}</article><div class="notes-grid">${noteCards}</div><div class="writing-follow"><p>Follow future notebook entries.</p><a class="text-link" href="/feed.xml">Subscribe via RSS ${arrow}</a></div></section>
  <section class="research-section" id="research"><div class="shell research-inner"><div class="research-intro"><p class="eyebrow"><span class="section-number">03</span>Research in progress</p><h2>Questions<br> worth testing.</h2><p>Proposed experiments on data quality, source support, and the behavior of AI systems. Each direction names a method and an intended output.</p>${link('/research/', 'Explore the research agenda', 'text-link')}<span class="agenda-note">Proposed studies. No published results or preprints listed.</span></div><ol class="research-list">${researchRows}</ol></div></section>
  <section class="about-section shell" id="about"><div class="about-label"><p class="eyebrow"><span class="section-number">04</span>About Owen</p><span class="about-monogram" aria-hidden="true">oc.</span></div><div class="about-copy"><h2>Useful tools.<br> Inspectable work.<br> Better questions.</h2><p>I’m Owen Crabbe. I work on applied AI systems for real estate research and on tools for planning, reflection, and evidence review. Cividian Site Diligence and Phroneme show how those interests become software.</p><p>I use AI-assisted development and research workflows. The case studies link implementation details to public artifacts, while the notebook records engineering decisions and open questions. Proposed research remains labeled until methods and results are published.</p>${link(site.github, 'Explore my public repositories', 'text-link')}</div></section>
  <section class="contact-section shell" id="contact"><div><p class="eyebrow">Research, engineering & collaboration</p><h2>Start with<br> <em>a useful question.</em></h2><p class="contact-description">Interested in the projects, an applied AI workflow, or a research collaboration? Share the question you’re working through.</p></div><div class="contact-actions">${link(`mailto:${site.email}?subject=Applied%20AI%20%2F%20research%20conversation`, 'Start a conversation', 'button button-primary')}<a class="contact-email" href="mailto:${site.email}">${site.email}</a><span class="contact-note">Opens your email app.</span></div></section>`, 'home-page');
}

function articleLayout({ path, title, description, eyebrow, intro, body, toc, links = '', cls = '', date = 'September 2026', publicationType = '' }) {
  const contents = toc.map(([id, text]) => `<li><a href="#${id}">${text}</a></li>`).join('');
  return page(path, title, description, `<div class="shell"><div class="article-heading"><a class="back-link" href="/${path.startsWith('/work/') ? '#work' : '#writing'}"><span aria-hidden="true">←</span> ${path.startsWith('/work/') ? 'Selected work' : 'The notebook'}</a><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="article-description">${intro}</p>${links ? `<div class="article-header-links">${links}</div>` : ''}</div><div class="article-layout"><aside class="article-sidebar"><span class="eyebrow">In this ${path.startsWith('/work/') ? 'project' : path.startsWith('/publications/') ? 'report' : 'note'}</span><ol>${contents}</ol><div class="article-sidebar-meta"><p>Owen Crabbe</p><span>${esc(date)}</span><span>${publicationType ? esc(publicationType) : 'Self-published ' + (path.startsWith('/work/') ? 'case study' : 'engineering note')}</span></div></aside><article class="article-body ${cls}">${body}<div class="article-end"><span class="brand-mark" aria-hidden="true"></span><p>Have a question or a useful counterexample?</p>${link(`mailto:${site.email}`, 'Start a conversation')}</div></article></div></div>`, 'article-page');
}

function cividian() {
  return articleLayout({ path: '/work/cividian/', title: 'Cividian Site Diligence', description: 'An evidence-led site investigation pipeline. A case study of documented architecture, source boundaries, and proposed evaluation.', eyebrow: 'Case study / Applied AI · Civic intelligence', intro: 'From a site question to a source-backed investigation brief—with explicit assumptions and questions still to verify.', body: caseStudy, toc: [['problem', 'The investigation problem'], ['architecture', 'The system architecture'], ['boundaries', 'Evidence boundaries'], ['evaluation', 'Evaluation'], ['takeaways', 'The larger idea']], links: `${link(site.repo, 'Public repository', 'button button-primary')}${link(site.demo, 'Project demo', 'text-link')}` });
}

function mindforge() {
  return articleLayout({ path: '/work/mindforge/', title: phronemeProject.title, description: phronemeProject.description, eyebrow: phronemeProject.eyebrow, intro: phronemeProject.intro, body: phronemeProject.body, toc: [['product', 'From toolkit to product'], ['contract', 'The evidence contract'], ['workflow', 'The browser-local loop'], ['evaluation', 'Tests and evaluation']], links: `${link(site.fitnessLab, 'Try Fitness Lab', 'button button-primary')}${link(site.phroneme, 'Phroneme product', 'text-link')}${link(site.mindforge, 'Public source', 'text-link')}` });
}

function notePage(note) {
  const toc = note.slug === 'evidence-as-interface' ? [['source-trail', 'The source trail'], ['claim-types', 'Different claim types'], ['unknowns', 'Preserving unknowns'], ['measure', 'What to measure']] : [['layers', 'Layers of correctness'], ['fixtures', 'Reproducible fixtures'], ['live-eval', 'Live evaluation'], ['receipts', 'Reproducible receipts']];
  return articleLayout({ path: `/writing/${note.slug}/`, title: note.title, description: note.description, eyebrow: `Engineering note / ${note.reading} · September 2026`, intro: note.description, body: articleBodies[note.slug], toc });
}

function researchPage() {
  const studies = research.map(item => `<section class="study" id="study-${item.number}"><div class="study-top"><span class="eyebrow">Study ${item.number}</span><span class="research-state">Proposed</span></div><h2>${item.title}</h2><p class="study-question">${item.description}</p><h3>Experiment direction</h3><p>${item.method}</p><h3>Intended publication</h3><p>${item.output}</p></section>`).join('');
  return page('/research/', 'Questions worth testing', 'A proposed research agenda on civic data curation, claim-level evidence, temporal reasoning, and abstention.', `<div class="shell"><div class="article-heading"><a class="back-link" href="/"><span aria-hidden="true">←</span> Home</a><p class="eyebrow">Research agenda / Proposed work</p><h1>Questions<br> worth testing.</h1><p class="article-description">A plan to turn engineering intuitions into reproducible experiments on data quality and evidence-bounded AI.</p></div><div class="research-page-layout"><aside class="research-page-aside"><p class="eyebrow">The standard</p><p>Freeze the question.<br> Expose the method.<br> Publish the boundary.</p><span>These are proposed studies. Experiments, datasets, measurements, and results have not yet been published.</span></aside><div class="research-studies">${studies}<section class="study principles-study"><p class="eyebrow">Across every study</p><h2>Make the result inspectable.</h2><ul><li>Document data rights, collection, exclusions, and source dates.</li><li>Keep held-out evaluation material separate from development data.</li><li>Publish baselines and ablations before claiming improvement.</li><li>Report unsupported answers, abstention, latency, and cost.</li><li>Include failure cases and the limits of the conclusion.</li></ul><p>These directions grow out of the public <a href="/work/cividian/">Cividian Site Diligence</a> and <a href="/work/mindforge/">Phroneme</a> projects. Their purpose is to produce original evidence, not to imply results that already exist.</p></section></div></div></div><section class="contact-section shell"><div><p class="eyebrow">Research conversations</p><h2>A better question<br> <em>is a useful start.</em></h2></div>${link(`mailto:${site.email}`, site.email, 'contact-link')}</section>`, 'research-page');
}

function methodsReportPage() {
  const toc = [['abstract','Abstract'],['1-introduction','Introduction'],['2-related-work-and-contribution-boundary','Related work'],['3-public-system-and-evidence-contract','System and evidence'],['4-available-software-validation-evidence','Software evidence'],['5-prospective-evaluation-protocol','Proposed evaluation'],['6-reproducibility-and-governance','Reproducibility'],['7-limitations-and-conclusion','Limits and conclusion'],['author-declarations','Author declarations'],['references','References']];
  return articleLayout({path:'/publications/'+methodsReport.slug+'/',title:methodsReport.title,description:methodsReport.description,eyebrow:'Technical report / '+methodsReport.status+' · '+methodsReport.peerReview,intro:methodsReport.subtitle,body:'<p class="report-release-note">Self-published technical report. Not peer reviewed. Published 2 October 2026. The proposed evaluation has not been executed.</p>'+methodsReport.body,toc,links:link(methodsReport.download,'Download manuscript (DOCX)','button button-primary'),cls:'methods-report',date:methodsReport.date,publicationType:'Self-published technical report · Not peer reviewed'});
}

function notFound() {
  return page('/404/', 'Page not found', 'Return to Owen Crabbe’s portfolio.', `<section class="shell not-found"><p class="eyebrow">404 / No page here</p><h1>Back to<br> <em>the work.</em></h1><p>This address does not point to a published page.</p><a class="button button-primary" href="/">Go to the homepage <span aria-hidden="true">↗</span></a></section>`);
}

export const pages = [
  { path: '/', html: home() },
  { path: '/work/cividian/', html: cividian() },
  { path: '/work/mindforge/', html: mindforge() },
  ...notes.map(note => ({ path: `/writing/${note.slug}/`, html: notePage(note) })),
  { path: '/research/', html: researchPage() },
  { path: '/publications/'+methodsReport.slug+'/', html: methodsReportPage() },
  { path: '/404/', html: notFound() },
];
