import { methodsReport } from './reports.mjs';
import { site, research, notes, caseStudy, articleBodies, phronemeProject } from './content.mjs';

const esc = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[c]));
const arrow = '<span aria-hidden="true">↗</span>';
const link = (url, label, classes = '') => `<a class="${classes}" href="${esc(url)}">${label} ${arrow}</a>`;

function header() {
  return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="shell header-inner"><a class="wordmark" href="/" aria-label="Owen Crabbe home"><span class="brand-mark" aria-hidden="true"></span>owen crabbe<span class="wordmark-period">.</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="site-nav">Menu <span aria-hidden="true">+</span></button><nav id="site-nav" aria-label="Main navigation"><a href="/#work">Work</a><a href="/#writing">Writing</a><a href="/research/">Research</a><a href="/#about">About</a></nav>${link(`mailto:${site.email}`, 'Get in touch', 'header-contact')}</div></header>`;
}

function footer() {
  return `<footer class="site-footer"><div class="shell footer-inner"><p>© 2026 Owen Crabbe</p><p>Applied AI. Open questions. Inspectable work.</p><div>${link(site.github, 'GitHub')}${link(`mailto:${site.email}`, 'Email')}</div></div></footer>`;
}

function page(path, title, description, body, cls = '') {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} — Owen Crabbe</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#f8f7f3"><link rel="canonical" href="${site.origin}${path}"><meta property="og:title" content="${esc(title)} — Owen Crabbe"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="${(path.includes('/writing/') || path.includes('/publications/')) ? 'article' : 'website'}"><meta property="og:url" content="${site.origin}${path}"><meta property="og:site_name" content="Owen Crabbe"><meta name="twitter:card" content="summary"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/styles.css"><script src="/assets/main.js" defer></script></head><body class="${cls}">${header()}<main id="main">${body}</main>${footer()}</body></html>`;
}

function sectionHeading(number, eyebrow, title, extra = '') {
  return `<div class="section-heading"><div><p class="eyebrow"><span class="section-number">${number}</span>${eyebrow}</p><h2>${title}</h2></div>${extra}</div>`;
}

function pipeline() {
  return `<aside class="principle-card" aria-labelledby="principle-heading"><div class="principle-top"><span class="eyebrow">Working principle 001</span><span class="principle-index" aria-hidden="true">↗</span></div><h2 id="principle-heading">An answer should<br>keep its evidence.</h2><div class="pipeline"><div class="pipeline-row"><span class="pipeline-node" aria-hidden="true">01</span><div><span class="pipeline-label">A real-world question</span><span class="pipeline-hint">Start with the decision.</span></div></div><div class="pipeline-row"><span class="pipeline-node" aria-hidden="true">02</span><div><span class="pipeline-label">Sources & assumptions</span><span class="pipeline-hint">Make the inputs inspectable.</span></div></div><div class="pipeline-row"><span class="pipeline-node" aria-hidden="true">03</span><div><span class="pipeline-label">An evidence-bounded answer</span><span class="pipeline-hint">Carry uncertainty forward.</span></div></div></div><div class="inspector"><p class="inspector-label">Inspect the principle</p><div class="inspector-controls" role="group" aria-label="Evidence principle"><button data-evidence="sources" aria-pressed="true">Sources</button><button data-evidence="decisions" aria-pressed="false">Decisions</button><button data-evidence="boundaries" aria-pressed="false">Boundaries</button></div><div class="inspector-output" aria-live="polite" aria-atomic="true"><h3 id="inspector-title">Keep the source trail.</h3><p id="inspector-copy">A useful claim points to the material that supports it. The evidence stays available for the reader to inspect.</p></div></div></aside>`;
}

function projectVisual() {
  return `<div class="project-visual" role="img" aria-label="Conceptual system sketch: evidence sources connect to analysis and an investigation brief."><div class="visual-label"><span class="status-dot" aria-hidden="true"></span> System sketch</div><svg class="map-grid" viewBox="0 0 600 460" aria-hidden="true"><defs><pattern id="grid" width="42" height="42" patternUnits="userSpaceOnUse"><path d="M 42 0 L 0 0 0 42" fill="none" stroke="currentColor" stroke-width="1"/></pattern></defs><rect width="600" height="460" fill="url(#grid)"/><path d="M-20 310L138 192L236 256L390 100L620 216M-10 40L180 166L280 136L446 298L600 274M66 500L210 320L156 244L286 -25" fill="none" stroke="currentColor" stroke-width="2"/><path d="M242 222L318 176L384 216L338 284L266 272Z" fill="currentColor" opacity=".18"/><path d="M242 222L318 176L384 216L338 284L266 272Z" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="315" cy="230" r="7" fill="#e0ffb7"/><circle cx="315" cy="230" r="18" fill="none" stroke="#e0ffb7" stroke-width="1"/></svg><div class="map-note map-note-one"><span>01 / Source evidence</span><strong>Traceable inputs</strong><div class="tiny-line"></div><div class="tiny-line short"></div></div><div class="map-note map-note-two"><span>02 / Analysis</span><strong>Explicit assumptions</strong><div class="evidence-tags"><i>Sources</i><i>Scenarios</i></div></div><div class="map-note map-note-three"><span>03 / Investigation brief</span><strong>Questions to verify <b aria-hidden="true">↗</b></strong><div class="tiny-line"></div><div class="tiny-line short"></div></div><span class="visual-coordinate">Sources → reasoning → review</span></div>`;
}

function home() {
  const noteCards = notes.map(note => `<article class="note-card"><p class="eyebrow">${note.category}<span class="note-number">${note.number}</span></p><h3><a href="/writing/${note.slug}/">${note.title}</a></h3><p>${note.description}</p><div class="note-bottom"><span>${note.reading}</span>${link(`/writing/${note.slug}/`, '<span class="sr-only">Read '+note.title+'</span>', 'round-arrow')}</div></article>`).join('');
  const researchRows = research.map(item => `<li><span class="research-number">${item.number}</span><div><h3>${item.title}</h3><p>${item.description}</p></div><span class="research-state">Proposed</span></li>`).join('');
  return page('/', 'Applied AI, grounded in evidence', 'Owen Crabbe builds applied AI tools and publishes engineering notes on evidence, agent workflows, and reproducible research.', `
  <section class="hero shell"><div class="hero-copy"><p class="eyebrow"><span class="blue-rule" aria-hidden="true"></span>The work of Owen Crabbe</p><h1>Applied AI,<br>grounded in<br><em>evidence.</em></h1><p class="hero-description">Building useful systems from messy, real-world information. Making the work—and the questions behind it—open to inspection.</p><div class="hero-actions"><a class="button button-primary" href="#work">Explore the work <span aria-hidden="true">↓</span></a><a class="text-link" href="#writing">Read the notebook ${arrow}</a></div><p class="hero-disciplines">Agent tooling <span aria-hidden="true">/</span> Civic intelligence <span aria-hidden="true">/</span> Reproducible research</p></div>${pipeline()}</section>
  <div class="shell"><div class="hero-bottom"><span>Software that explains its work.</span><span>From project to question to experiment.</span><span class="scroll-hint" aria-hidden="true">↓</span></div></div>
  <section class="work-section shell" id="work">${sectionHeading('01', 'Selected work', 'Systems, with a source trail.', '<p class="section-aside">Public code. Documented decisions.<br>Honest boundaries.</p>')}
  <article class="featured-project"><div class="project-copy"><p class="eyebrow"><span class="project-kicker">Civic intelligence</span><span>Public project</span></p><h3><a href="/work/cividian/">Cividian<br>Site Diligence<span aria-hidden="true">↗</span></a></h3><p>An investigation pipeline connecting site identity, source evidence, financial scenarios, and bounded AI reasoning to an inspectable brief.</p><div class="project-tags"><span>Evidence retrieval</span><span>Deterministic analysis</span><span>Citation checks</span></div><div class="project-links">${link('/work/cividian/', 'Read the case study', 'project-main-link')}${link(site.repo, 'View source')}</div></div>${projectVisual()}</article>
  <article class="secondary-project"><div class="secondary-icon" aria-hidden="true">[↗]</div><div><p class="eyebrow">Working product · Open-source evidence contract</p><h3><a href="/work/mindforge/">${phronemeProject.title}</a></h3><p>${phronemeProject.summary}</p></div>${link('/work/mindforge/', 'Explore project', 'secondary-link')}</article></section>
  <section class="writing-section shell" id="writing">${sectionHeading('02', 'The notebook', 'Thinking through the build.', '<p class="section-aside">Self-published engineering notes.<br>Ideas with their limits attached.</p>')}<article class="report-card"><p class="eyebrow">Technical report · ${esc(methodsReport.status)} · ${esc(methodsReport.peerReview)}</p><h3><a href="/publications/${methodsReport.slug}/">${esc(methodsReport.title)}</a></h3><p>${esc(methodsReport.description)}</p><p>Published ${esc(methodsReport.date)}. No live benchmark outcomes are reported.</p>${link('/publications/'+methodsReport.slug+'/', 'Read the technical report', 'text-link')}</article><div class="notes-grid">${noteCards}</div></section>
  <section class="research-section" id="research"><div class="shell research-inner"><div class="research-intro"><p class="eyebrow"><span class="section-number">03</span>Research agenda</p><h2>Questions<br>worth testing.</h2><p>A direction for the next body of work: controlled experiments on data quality, source support, and the behavior of AI systems.</p>${link('/research/', 'See the research agenda', 'text-link')}<span class="agenda-note">Proposed studies. No results claimed.</span></div><ol class="research-list">${researchRows}</ol></div></section>
  <section class="about-section shell" id="about"><div class="about-label"><p class="eyebrow"><span class="section-number">04</span>About Owen</p><span class="about-monogram" aria-hidden="true">oc.</span></div><div class="about-copy"><h2>Building at the intersection<br>of human cognition<br>and AI agents.</h2><p>I’m Owen Crabbe. My work brings together agent tooling, civic intelligence, and reproducible research. I’m interested in systems that help people work through complex questions while keeping the evidence in view.</p><p>I use AI-assisted development and research workflows. The implementation and technical claims are linked to public source for inspection. These notes are self-published; proposed studies are labeled as proposed.</p>${link(site.github, 'Follow the work on GitHub', 'text-link')}</div></section>
  <section class="contact-section shell" id="contact"><div><p class="eyebrow">Hiring & collaboration</p><h2>Let’s build something<br><em>worth understanding.</em></h2><p class="contact-description">Open to conversations about applied AI, agent tooling, and research engineering.</p></div>${link(`mailto:${site.email}`, site.email, 'contact-link')}</section>`, 'home-page');
}

function articleLayout({ path, title, description, eyebrow, intro, body, toc, links = '', cls = '', date = 'September 2026', publicationType = '' }) {
  const contents = toc.map(([id, text]) => `<li><a href="#${id}">${text}</a></li>`).join('');
  return page(path, title, description, `<div class="shell"><div class="article-heading"><a class="back-link" href="/${path.startsWith('/work/') ? '#work' : '#writing'}"><span aria-hidden="true">←</span> ${path.startsWith('/work/') ? 'Selected work' : 'The notebook'}</a><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="article-description">${intro}</p>${links ? `<div class="article-header-links">${links}</div>` : ''}</div><div class="article-layout"><aside class="article-sidebar"><span class="eyebrow">In this ${path.startsWith('/work/') ? 'project' : path.startsWith('/publications/') ? 'report' : 'note'}</span><ol>${contents}</ol><div class="article-sidebar-meta"><p>Owen Crabbe</p><span>${esc(date)}</span><span>${publicationType ? esc(publicationType) : 'Self-published ' + (path.startsWith('/work/') ? 'case study' : 'engineering note')}</span></div></aside><article class="article-body ${cls}">${body}<div class="article-end"><span class="brand-mark" aria-hidden="true"></span><p>Have a question or a useful counterexample?</p>${link(`mailto:${site.email}`, 'Start a conversation')}</div></article></div></div>`, 'article-page');
}

function cividian() {
  return articleLayout({ path: '/work/cividian/', title: 'Cividian Site Diligence', description: 'An evidence-led site investigation pipeline. A case study of documented architecture, source boundaries, and proposed evaluation.', eyebrow: 'Case study / Applied AI · Civic intelligence', intro: 'From a site question to a source-backed investigation brief—with explicit assumptions and questions still to verify.', body: caseStudy, toc: [['problem', 'The investigation problem'], ['architecture', 'The system architecture'], ['boundaries', 'Evidence boundaries'], ['evaluation', 'Evaluation'], ['takeaways', 'The larger idea']], links: `${link(site.repo, 'Public repository', 'button button-primary')}${link(site.demo, 'Project demo', 'text-link')}` });
}

function mindforge() {
  return articleLayout({ path: '/work/mindforge/', title: phronemeProject.title, description: phronemeProject.description, eyebrow: phronemeProject.eyebrow, intro: phronemeProject.intro, body: phronemeProject.body, toc: [['product', 'From toolkit to product'], ['contract', 'The evidence contract'], ['workflow', 'The browser-local loop'], ['evaluation', 'Tests and evaluation']], links: `${link(site.fitnessLab, 'Try Fitness Lab', 'button button-primary')}${link(site.phroneme, 'Phroneme product', 'text-link')}${link(site.mindforge, 'Public source', 'text-link')}` });
}

function notePage(note) {
  const toc = note.slug === 'evidence-as-interface' ? [['source-trail', 'The source trail'], ['claim-types', 'Different claim types'], ['unknowns', 'Preserving unknowns'], ['measure', 'What to measure']] : [['layers', 'Layers of correctness'], ['fixtures', 'Reproducible fixtures'], ['live-eval', 'Live evaluation'], ['receipts', 'Reproducible receipts']];
  return articleLayout({ path: `/writing/${note.slug}/`, title: note.title, description: note.description, eyebrow: `Engineering note / ${note.reading} · September 2026`, intro: note.description, body: articleBodies[note.slug], toc });
}

function researchPage() {
  const studies = research.map(item => `<section class="study" id="study-${item.number}"><div class="study-top"><span class="eyebrow">Study ${item.number}</span><span class="research-state">Proposed</span></div><h2>${item.title}</h2><p class="study-question">${item.description}</p><h3>Experiment direction</h3><p>${item.method}</p><h3>Intended publication</h3><p>${item.output}</p></section>`).join('');
  return page('/research/', 'Questions worth testing', 'A proposed research agenda on civic data curation, claim-level evidence, temporal reasoning, and abstention.', `<div class="shell"><div class="article-heading"><a class="back-link" href="/"><span aria-hidden="true">←</span> Home</a><p class="eyebrow">Research agenda / Proposed work</p><h1>Questions<br>worth testing.</h1><p class="article-description">A plan to turn engineering intuitions into reproducible experiments on data quality and evidence-bounded AI.</p></div><div class="research-page-layout"><aside class="research-page-aside"><p class="eyebrow">The standard</p><p>Freeze the question.<br>Expose the method.<br>Publish the boundary.</p><span>These are proposed studies. Experiments, datasets, measurements, and results have not yet been published.</span></aside><div class="research-studies">${studies}<section class="study principles-study"><p class="eyebrow">Across every study</p><h2>Make the result inspectable.</h2><ul><li>Document data rights, collection, exclusions, and source dates.</li><li>Keep held-out evaluation material separate from development data.</li><li>Publish baselines and ablations before claiming improvement.</li><li>Report unsupported answers, abstention, latency, and cost.</li><li>Include failure cases and the limits of the conclusion.</li></ul><p>These directions grow out of the public <a href="/work/cividian/">Cividian Site Diligence</a> and <a href="/work/mindforge/">Phroneme</a> projects. Their purpose is to produce original evidence, not to imply results that already exist.</p></section></div></div></div><section class="contact-section shell"><div><p class="eyebrow">Research conversations</p><h2>A better question<br><em>is a useful start.</em></h2></div>${link(`mailto:${site.email}`, site.email, 'contact-link')}</section>`, 'research-page');
}

function methodsReportPage() {
  const toc = [['abstract','Abstract'],['1-introduction','Introduction'],['2-related-work-and-contribution-boundary','Related work'],['3-public-system-and-evidence-contract','System and evidence'],['4-available-software-validation-evidence','Software evidence'],['5-prospective-evaluation-protocol','Proposed evaluation'],['6-reproducibility-and-governance','Reproducibility'],['7-limitations-and-conclusion','Limits and conclusion'],['author-declarations','Author declarations'],['references','References']];
  return articleLayout({path:'/publications/'+methodsReport.slug+'/',title:methodsReport.title,description:methodsReport.description,eyebrow:'Technical report / '+methodsReport.status+' · '+methodsReport.peerReview,intro:methodsReport.subtitle,body:'<p class="report-release-note">Self-published technical report. Not peer reviewed. Published 2 October 2026. The proposed evaluation has not been executed.</p>'+methodsReport.body,toc,links:link(methodsReport.download,'Download manuscript (DOCX)','button button-primary'),cls:'methods-report',date:methodsReport.date,publicationType:'Self-published technical report · Not peer reviewed'});
}

function notFound() {
  return page('/404/', 'Page not found', 'Return to Owen Crabbe’s portfolio.', `<section class="shell not-found"><p class="eyebrow">404 / No page here</p><h1>Back to<br><em>the work.</em></h1><p>This address does not point to a published page.</p><a class="button button-primary" href="/">Go to the homepage <span aria-hidden="true">↗</span></a></section>`);
}

export const pages = [
  { path: '/', html: home() },
  { path: '/work/cividian/', html: cividian() },
  { path: '/work/mindforge/', html: mindforge() },
  ...notes.map(note => ({ path: `/writing/${note.slug}/`, html: notePage(note) })),
  { path: '/research/', html: researchPage() },
  { path: '/publications/'+methodsReport.slug+'/', html: methodsReportPage() },
  { path: '/404/', html: notFound() },
];
